import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';
import axios from 'axios';
import Feeder from '../models/Location/Feeder.js';
import LGA from '../models/Location/LGA.js';
import Ward from '../models/Location/Ward.js';
import InjectionSubstation from '../models/Location/InjectionSubstation.js';
import { slugify } from '../utils/slugGenerator.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../.env') });

const OCR_TEXT = `
1 A 11KV AHMADU BELLO CLUB INJECTION SUBSTATION AHMADU BELLO WAYAND MURTALA MUHD WAY KANO 20
2 A 11KV APEX FADAMA INJECTION SUBSTATION CBN, KATSINA 20
3 A 11KV AUDU BAKO CLUB INJECTION SUBSTATION AHMADU BELLO WAYAND MURTALA MUHD WAY KANO 20
4 A 11KV BANK ROAD CLUB INJECTION SUBSTATION BANK ROAD KANO 20
5 A 11KV BOMPAI BRISCOE INJECTION SUSTATION BOMPAI ROAD KANO 20
6 A 11KV CERAMIC ABATTOIR INJECTION SUBSTATION CHALLAWA INDUSTRIAL AREA 20
7 A 11KV CHALLAWA WATER PLANT CHALLAWA INJECTION SUBSTATION WATER PLANT CHALLAWA 20
8 A 11KV DALA FOODS GONGONI INJECTION SUBSTATION SHARADA INDUSTRIAL KANO 20
9 A 11KV DR BALA BUK INJECTION SUBSTATION R/ZAKI ALONG GWARZO ROAD, BARAKAT STORE, JAIZ BANK AND ZENITH BANK. 20
10 A 11KV FANTAI HADEJIA NIPP INJECTION SUB STATION BANK ROAD, KANO ROAD HADEJIA JIGAWA STATE 20
11 A 11KV FUNTUA TEXTILE MILL TEXTILE INJECTION SUBSTATION FUNTUA TEXTILE MILL 20
12 A 11KV FUNTUA WATER WORKS TEXTILE INJECTION SUBSTATION FUNTUA WATER WORKS 20
13 A 11KV GOVERNMENT HOUSE DUTSE DUTSE INJECTION SUBSTATION GOVERNMENT HOUSE AND MINISTRY OF LAND DUTSE. 20
14 A 11KV GWARZO ROAD 11KV GWARZO ROAD BUK INJECTION SUBSTATION 20
15 A 11KV INDUSTRIAL KATSINA ROAD INJECTION SUBSTATION FUNTUA INDUSTRIAL 20
16 A 11KV LAMBISA FARM CENTER INJECTION SUBSTATION HOTORO GRA, MAIDUGURI ROAD, KANO 20
17 A 11KV MAIMALARI BRISCOE INJECTION SUSTATION MAIMALARI BOMPAI KANO 20
18 A 11KV NBC ABATTOIR INJECTION SUBSTATION CHALLAWA INDUSTRIAL AREA 20
19 A 11KV NUHU SUNUSI 20
20 A 11KV RIJIMA RICE DAURA INJECTION SUBSTATION RIJIMA BARRACK, KATSINA 20
21 A 11KV TAMBURAWA WATER PLANT TAMBURAWA INJECTION SUBSTATION WATER PLANT TAMBURAWA 20
22 A 11KV TOKARAWA DAKATA TS FRANCE ROAD, KANO 20
23 A 11KV WUDIL COMMERCIAL WUDIL INJECTION SUBSTATION GAYA ROAD WUDIL COMMERCIAL AREA 20
24 A 11KV YUSUF ROAD BRISCOE INJECTION SUSTATION YUSUF ROAD KANO 20
25 A 33KV AJIWA WATER WORKS KATSINA TS NEW GOVT HOUSE, SSS OFFICE, INEC TOURIST LODGE, AJIWA WATER TREATMENT 20
26 A 33KV ANGELS KUMBOTSO TS SHARADA INDUSTRIAL AREA 20
27 A 33KV ATM KUMBOTSO TS CHALLAWA INDUSTRIAL AREA 20
28 A 33KV BIRNIN KUDU DUTSE TS KWANAR HUGUMA, YALWAN DAMAI AND GWARAM TOWN. 20
29 A 33KV BRISCOE DAKATA TS INDEPENDENCE ROAD 20
30 A 33KV CBN DAN AGUNDI TS ADO BAYERO MALL, BRISTOL HOTEL,STATE ROAD, AUDU BAKO WAY AND POST OFFICE ROAD KANO 20
31 A 33KV CHALLAWA WATER WORKS TAMBURAWA TS WATER PLANT CHALLAWA 20
32 A 33KV CLUB DAN AGUNDI TS KANO CLUB INJECTION SUBSTATION 20
33 A 33KV COCA COLA TAMBURAWA TS CHALLAWA INDUSTRIAL AREA 20
34 A 33KV DAN AGUNDI 1 DAN AGUNDI TS DANAGUNDI INJECTION SUB STATION KANO CITY 20
35 A 33KV DAN AGUNDI 2 DAN AGUNDI TS DAN AGUNDI INJECTION SUBSTATION, BUK ROAD, KANO 20
36 A 33KV DANGOTE KUMBOTSO TS SHARADA INDUSTRIAL AREA 20
37 A 33KV DAURA TEXTILE INJECTION SUBSTATION ENTIRE MAIRUWA TOWN, KATSINA. 20
38 A 33KV DAWANAU INDUSTRIAL BUKAVU INJECTION SUBSTATION POLEWIRE LINE, JAJIRA, KATSINAWA AND DAWANAU AREAS. 20
39 A 33KV DR JIMETA 20
40 A 33KV DUTSE DUTSE TS FUD, DUTSE. 20
41 A 33KV FLOUR MILLS DAKATA TS DAKATA SMALL SCALE AND BOMPAI AREA. 20
42 A 33KV GASKIYA 33KV GASKIYA DAKATA TS 20
43 A 33KV HADEJIA HADEJIA TS HADEJIA, BIRNIWA, UNIVERSITY, GUMEL, KAFIN HAUSA 20
44 A 33KV JODA DAKATA TS HADEJIA ROAD 20
45 A 33KV KAFIN HAUSA HADEJIA TS HADEJIA, K/HAUSA AND KANO ROAD JIGAWA STATE 20
46 A 33KV KATSINA ROAD FUNTUA TS KATSINA ROAD INJECTION SUBSTATION, FUNTUA 20
47 A 33KV KOFAR GUGA KATSINA TS FEDERAL TEACHING HOSPITAL KATSINA 20
48 A 33KV KURNA KATSINA TS KAITA, DANKAMA, MAKURDA AND HIGH COURT, KATSINA. 20
49 A 33KV LAW SCHOOL DANGORA TS BAGAUDA, TARAU AND GARIN MALLAM AREA. 20
50 A 33KV MAMUDA KUMBOTSO TS CHALLAWA INDUSTRIAL AREA 20
51 A 33KV MTN DAKATA TS BOMPAI INDUSTRIAL AREA 20
52 A 33KV NB CERAMIC DANGORA TS NB CERAMIC CO K/DANGORA, ZARIA ROAD KANO 20
53 A 33KV NNPC DAKATA TS HOTORO NNPC BYE BASS, TINSHAMA AND LADANAI AREA. 20
54 A 33KV POWER HOUSE KATSINA TS IBB WAY INJECTION SUB STATION KATSINA URBAN 20
55 A 33KV RICE FIELD TAMBURAWA TS GWARZO ROAD, INDUSTRIAL AREA 20
56 A 33KV RICE MILLS GAGARAWA TS GUJUNGU, JIGAWA RICE MILLS, GAGARAWA 20
57 A 33KV RUMMAWA DAKATA TS RUMMAWA INDUSTRIAL HUB 20
58 A 33KV SARKIN YAKI 33KV SARKIN YAKI 33KV SARKIN YAKI 20
59 A 33KV SHARADA BATA KUMBOTSO TS SHARADA BATA INJECTION SUBSTATION 20
60 A 33KV SMALL SCALE DAKATA TS DAKATA SMALL SCALE 20
61 A 33KV SPANISH 1 KUMBOTSO TS SHARADA INDUSTRIAL AREA 20
62 A 33KV SPANISH 2 KUMBOTSO TS SHARADA INDUSTRIAL AREA 20
63 A 33KV TAMBURAWA WATER WORKS TAMBURAWA TS WATER TREATMENT PLANT TAMBURAWA 20
64 A 33KV TEXTILE FUNTUA TS FUNTUA TEXTILE,MAIRUWA ROAD FUNTUA 20
65 A 33KV UNIVERSITY HADEJIA TS HADEJIA, BIRNIWA, UNIVERSITY, GUMEL, KAFIN HAUSA 20
66 A 33KV WUDIL WUDL TS KUST, WUDIL 20
67 A 33KV ZARIA ROAD DAN AGUNDI TS AKTH,NA'IBAWA, ZARIA ROAD KANO 20
68 B 11KV ABUJA ROAD IDH INJECTION SUBSTATION FRANCE ROAD, COURT ROAD AND MIDDLE ROAD. 16
69 B 11KV AIRPORT ROAD PRP INJECTION SUBSTATION AIRPORT ROAD, FOUTAIN ESTATE AND JABA AREA. 16
70 B 11KV AJASA DAN AGUNDI INJECTION SUBSTATION KANO TRADE FARE, ZOO ROAD AND AJASA 16
71 B 11KV BADAWA CLUB INJECTION SUBSTATION BADAWA LAYOUT, LAMIDO CRESCENT AND SARDAUNA CRESCENT. 16
72 B 11KV BAYAJIDDA DAURA INJECTION SUBSTATION DAURA METROPOLITAN 16
73 B 11KV BELLO DANDAGO RADIO HOUSE INJECTION SUBSTATION RADIO HOUSE. 16
74 B 11KV DAKATA KAWAJI INJECTION SUBSTATION DAKATA AND KAWAJI AREA. 16
75 B 11KV DANDAGORO IBB WAY INJECTION SUBSTATION FEDERAL SECRETARIAT KATSINA AND DANDAGORO 16
76 B 11KV DANLADI NASIDI MARIRI INJECTION SUBSTATION DANLADI NASIDI HOUSING ESTATE. 16
77 B 11KV DAURAMA DAURA INJECTION SUBSTATION DAURA METROPOLITAN 16
78 B 11KV GARU DUTSE INJECTION SUBSTATION FAGOJI AND GARU EMIRS PALACE ROAD. 16
79 B 11KV HASSAN USMAN ROAD FADAMA INJECTION SUBSTATION HASSAN USMAN KATSINA ROAD AND GRA KATSINA. 16
80 B 11KV HAUSAWA ZARIA ROAD INJECTION SUBSTATION BAWO ROAD AND HAUSAWA MASALLACHIN MURTALA ROAD. 16
81 B 11KV HOUSING ESTATE SHARADA INJECTION SUBSTATION HOUSING ESTATE AREA. 16
82 B 11KV IBRAHIM TAIWO DAN AGUNDI INJECTION SUBSTATION IBRAHIM TOIWO ROAD, KOFAR DAN AGUNDI AND KWARI MARKET 16
83 B 11KV INDEPENDENCE BRISCOE INJECTION SUBSTATION INDEPENDENCE ROAD, GAWAUNA AND KINGS GARDEN AREA. 16
84 B 11KV KABUGA GORON DUTSE INJECTION SUBSTATION GADON KAYA, SALANTA AND KUNTAU AREA. 16
85 B 11KV KADARKO FADAMA INJECTION SUBSTATION KADARKO AREA, KATSINA 16
86 B 11KV KARKASARA ZARIA ROAD INJECTION SUBSTATION KARKASARA, HASSAN GWARZO SECONDARY AND ROYAL CITY ESTATE. 16
87 B 11KV LOW COST IBB WAY NIPP INJECTION SUBSTATION LOW COST, KATSINA 16
88 B 11KV MAJE HADEJIA INJECTION SUBSTATION MALAM MADORI ROAD. 16
89 B 11KV MAJESTIC BIRNIN KUDU INJECTION SUBSTATION MAJESTIC RICE COMPANY. 16
90 B 11KV MASARAUTA NAIBAWA INJECTION SUBSTATION NAIBAWA ZARIA ROAD AND SAADATU RIMI COLLEGE OF EDUCATION. 16
91 B 11KV MURTALA MUHAMMED CLUB INJECTION SUBSTATION MURTALA MOHD WAY, FRANCEROAD AND IGBO ROAD 16
92 B 11KV NEW SITE BUK INJECTION SUBSTATION BUK NEW CAMPUS. 16
93 B 11KV NNDC SHARADA INJECTION SUBSTATION NNDC AND SHARADA AREA. 16
94 B 11KV NOMANSLAND BUKAVU INJECTION SUBSTATION NOMANSLAND AND KATSINA ROAD AREAS. 16
95 B 11KV RACE COURSE CLUB INJECTION SUBSTATION RACE COURSE ROAD, ALU AVENUE AND LAMIDO CRESCENT. 16
96 B 11KV SABON GARI IDH INJECTION SUBSTATION WEATHER HEAD, BAMA ROAD, GOLD COAST, IJEBU BALATUS AND ENUGU ROAD. 16
97 B 11KV SANI ABACHA WAY DUTSE NIPP INJECTION SUBSTATION BANK ROAD DUTSE AND G9 QUARTERS AREA. 16
98 B 11KV SHAGARI HADEJIA INJECTION SUBSTATION SHAGARI QUARTERS AND GRA HADEJIA 16
99 B 11KV SHARADA INDUSTRIAL SHARADA INJECTION SUBSTATION GIDAN MAZA, MEDILE AND SABUWAR GANDU AREA. 16
100 B 11KV TAKUR DUTSE NIPP INJECTION SUBSTATION TAKUR HOUSING ESTATE AND POLICE HEAD QUARTERS. 16
101 B 11KV TARAUNI FARM CENTER INJECTION SUBSTATION TARAUNI AND DAURAWA QUARTERS. 16
102 B 11KV YANKABA KAWAJI INJECTION SUBSTATION KAWAJI, YANKABA HADEJIA ROAD. 16
103 B 11KV YANLEMO NAIBAWA INJECTION SUBSTATION NAIBAWA ZARIA ROAD AND YANKATAKO AREA AND MAIKALWA AREA. 16
104 B 33KV AMPRI GLOBAL KANKIA TS AMPRI GLOBAL KANKIA AND ZONE WATER TREATMENT PLANT, DUTSINMA 16
105 B 33KV BUK DAN AGUNDI TS BUK ROAD, TUDUN YOLA AND R/ZAKI AREA. 16
106 B 33KV GAGARAWA GAGARAWA TS GAGARAWA TOWN ALONG HADEJIA ROAD. 16
107 B 33KV IDH DAKATA TS FRANCE ROAD, KANO 16
108 B 33KV KAITA KATSINA TS KAITA, DANKAMA, MAKURDA AND HIGH COURT, KATSINA. 16
109 B 33KV MAMMAN NASIR FUNTUA TS FUNTUA ROAD, MALUMFASHI INJECTION SUBSTATION. 16
110 B 33KV MUSAWA KANKIA TS KUSADA, JIKAMSHI, TSANYAWA AND GHARI. 16
111 B 33KV RIJIYAR ZAKI TAMBURAWA TS KUYAN TA INNA MADOBI ROAD, DANBARE, BUK NEW SITE AND R/ZAKI AREA. 16
112 C 11KV AMINU KANO GORON DUTSE INJECTION SUBSTATION KOFAR KANKASALI ROAD, TUDUN YOLA, BAJALLABE AND RIMIN ZAKARA AREA. 12
113 C 11KV BACHIRAWA BUKAVU INJECTION SUBSTATION KURNA AND RIJIYAR LEMO AREAS 12
114 C 11KV BCGA MALUMFASHI INJECTION SUBSTATION BCGA, MALUMFASHI, KATSINA 12
115 C 11KV BICHI TOWN BICHI INJECTION SUBSTATION BICHI MINI STADIUM, HAGAGAWA, FCE BICHI ROAD AND BICHI GENERAL HOSPITALS. 12
116 C 11KV CAMPUS LAW SCHOOL INJECTION SUBSTATION LAW SCHOOL CAMPUS BAGAUDA. 12
117 C 11KV CITY DAN AGUNDI INJECTION SUBSTATION EMIRS’ PALACE ROAD, DISO ROAD. 12
118 C 11KV DANTUNKU KAZAURE INJECTION SUBSTATION KAZAURE METROPOLITAN 12
119 C 11KV DUTSEN REME KATSINA ROAD INJECTION SUBSTATION DDUTIES REME, AREA, 12
120 C 11KV DUTSEN SAFE KOFAR GUGA INJECTION SUBSTATION DUTSEN SAFE LOW COST, SABON GIDA AND FILIN SUKUWA 12
121 C 11KV FAGGE IDH INJECTION SUBSTATION FAGGE AND KOFAR WAMBAI AND ZAGE AREA. 12
122 C 11KV FARAWA MARIRI INJECTION SUBSTATION MARIRI, FARAWA AND GERAWA AREA. 12
123 C 11KV FEDERAL SECRETARIAT BUKAVU INJECTION SUBSTATION GWAMMAJA HOUSING ESTATE, YAN RODI AND KWANAR TAYA AREA. 12
124 C 11KV FMC KOFAR GUGA INJECTION SUBSTATION KOFAR YANDAKA AND BEHIND FMC KATSINA. 12
125 C 11KV GALADIMA MALUMFASHI INJECTION SUBSTATION GALADIMA ROAD, MALUMFASHI, KATSINA. 12
126 C 11KV GRA IBB WAY INJECTION SUBSTATION GIDA DAWA, NYSC CAMP AND KWADO 12
127 C 11KV HOSPITAL ROAD KOFAR GUGA INJECTION SUBSTATION KOFAR GUGA, GAMBARAWA AND CPS KATSINA. 12
128 C 11KV HOTORO ZARIA ROAD INJECTION SUBSTATION HOTORO MAIDUGURI ROAD AND TINSHAMA AREA. 12
129 C 11KV JABIRI KATSINA ROAD INJECTION SUBSTATION JABIRI AREA, FUNTUA 12
130 C 11KV KANO ROAD IBB WAY INJECTION SUBSTATION IBB WAY, GORON GIDA AND RAFIN DADI 12
131 C 11KV KANTI KAZAURE INJECTION SUBSTATION KAZAURE METROPOLITAN 12
132 C 11KV KOFAR NAISA DAN AGUNDI INJECTION SUBSTATION KOFAR NAISA, GSS GWALE ROAD AND FILIN MUSHE. 12
133 C 11KV KOFAR NASSARAWA DAN AGUNDI INJECTION SUBSTATION KOFAR NASSARAWA AND YAKASAI AREAS 12
134 C 11KV KUNDILA ZARIA ROAD INJECTION SUBSTATION KUNDILA HOUSING ESTATE MAIDUGURI ROAD. 12
135 C 11KV LAMIDO CLUB INJECTION SUBSTATION LAMIDO ROAD, BADAWA AND KAWO AREA. 12
136 C 11KV LAUTAI GUMEL INJECTION SUBSTATION GUMEL EMIRS PALACE ROAD AND MAIGATARI AREA. 12
137 C 11KV LIMAWA DUTSE INJECTION SUBSTATION LIMAWA, GALMAWA AND GGC TILES. 12
138 C 11KV MAIDUGURI ROAD MARIRI INJECTION SUBSTATION HOTORO MAIDUGURI ROAD AND TINSHAMA AREA. 12
139 C 11KV MAKAMA WUDIL INJECTION SUBSTATION WUDIL TOWN AREA. 12
140 C 11KV MARHABA ZARIA ROAD INJECTION SUBSTATION COURT ROAD GYADI GYADI AND ZOO ROAD HOUSING ESTATE. 12
141 C 11KV MUHAMMED DIKKO KOFAR SAURI INJECTION SUBSTATION MUHD DISCO ROAD, KATSINA EMIR'S PLACE AND TUDUN WADA, KATSINA 12
142 C 11KV MUNDADU GONGONI INJECTION SUBSTATION MUNDADU AND KWARIN BARKA AREA. 12
143 C 11KV NAGOGGO FADAMA INJECTION SUBSTATION NAGOGO ROAD AND SABUWAR UNGUWA, KATSINA 12
144 C 11KV NAKOWA KATSINA ROAD INJECTION SUBSTATION NOKOWA AREA, FUNTUA 12
145 C 11KV NATSINTA KOFAR GUGA INJECTION SUBSTATION NATSINTA BARRACK, KATSINA 12
146 C 11KV ORTHOPAEDIC BUKAVU INJECTION SUBSTATION KOFAR RUWA, AMINU KANO WAY AND GORON DUTSE AREAS. 12
147 C 11KV PANSHEKARA CHALAWA INJECTION SUBSTATION PANSHEKARA AND KUMBOTSO AREA. 12
148 C 11KV SALLARI ZARIA ROAD INJECTION SUBSTATION SALLARI, SHEKA YARKASUWA AND ACI LAFIYA AREA. 12
149 C 11KV SANI MAINAGGE GORON DUTSE INJECTION SUBSTATION SANI MAINAGGE AND MANDAWARI AREA. 12
150 C 11KV SCHOOL OF NURSING BIRNIN KUDU INJECTION SUBSTATION SCHOOL OF NURSING AND PRISON FARM HOUSE ALONG MAIDUGURI ROAD. 12
151 C 11KV TIGA LAW SCHOOL INJECTION SUBSTATION BEBEJI AND TIGA TOWN. 12
152 C 11KV TOWN KATSINA ROAD INJECTION SUBSTATION DUTSEN REME AREA, FUNTUA 12
153 C 11KV TUKUNTAWA SHARADA INJECTION SUBSTATION TUKUNTAWA AND SHAGARI QUARTERS. 12
154 C 11KV UNGUWA UKU ZARIA ROAD INJECTION SUBSTATION UNGUWA UKU, NAIBAWA DANHASSAN LINE. 12
155 C 11KV ZAWACIKI ABATTOIR INJECTION SUBSTATION ALMUKAB HOUSING ESTATE, ZAWACHIKI AND GAIDA AREA. 12
156 C 33KV DANBATTA KANKIA TS CHARANCHI, BINDAWA, INGAWA, RONI GWIWA AND DANBATTA 12
157 C 33KV DUTSENMA KANKIA TS KANKIA METROPOLITAN, RADDA, DUTSINMA, KURFI, SAFANA AND DANMUSA 12
158 C 33KV FALGORE DANGORA TS FALGORE, GIDAN KWANO AND YALWAN PAKI AREA. 12
159 C 33KV GAIDA KUMBOTSO TS GAIDA AND ZAWACHIKI HOUSING ESTATE. 12
160 C 33KV GANO WUDIL TS GANO MAIDUGURI ROAD, MAKOLE, MARIRI AREA. 12
161 C 33KV GUMEL HADEJIA TS MALAM MADORI AND DANTANOMA AND GUMEL PALACE 12
162 C 33KV HON. ABUBAKAR BICHI TS BICHI METROPOLITAN 12
163 C 33KV KARAYE DANGORA TS KWANAR DANGORA, KIRU AND KARAYE TOWN. 12
164 C 33KV KAZAURE DAURA TS DAURA ROAD, KAZAURE INJECTION SUBSTATION 12
165 C 33KV MASHI DAURA TS KAGAWA, MASHI, DUTSI AND MANI 12
166 C 33KV WATARI BICHI TS WATARI WATER TREATMENT PLANT, BAGWAI AND SHANONO 12
167 D 11KV ARMY BARRACKS IBB WAY NIPP INJECTION SUBSTATION KOFAR KWAYA, YAHAYA MADAKI WAY AND RAHAMAWA. 8
168 D 11KV CHIRANCI GONGONI INJECTION SUBSTATION DORAYI SHIEK JAFAR MAHMUD ROAD AND CHIRANCHI AREA. 8
169 D 11KV FANISAU BUKAVU INJECTION SUBSTATION FANISAU ROAD, UNGOGO TOWN AND BACHIRAWA AREAS. 8
170 D 11KV GWAGWARWA BRISCOE INJECTION SUBSTATION GWAGWARWA, YANKAJI AND KWANAR JABA AREA. 8
171 D 11KV GWAMMAJA IDH INJECTION SUBSTATION GWAMMAJA AND ADAKAWA AREA. 8
172 D 11KV JAEN GONGONI INJECTION SUBSTATION JAEN AND SHAGO TARA AREAS. 8
173 D 11KV JAKARA GORON DUTSE INJECTION SUBSTATION GORON DUTSE PRISON ROAD AND JAKARA AREA. 8
174 D 11KV JAMAARE HADEJIA NIPP INJECTION SUBSTATION HADEJIA TOWN. 8
175 D 11KV KAURA GOJE PRP INJECTION SUBSTATION KAURA GOJE AND KWANA HUDU AREA. 8
176 D 11KV KOFAR FADA MUSAWA INJECTION SUBSTATION MUSAWA METROPOLITAN 8
177 D 11KV KOKI IDH INJECTION SUBSTATION KOKI AND BAKIN ZUWO AREAS. 8
178 D 11KV MAKWALLA MALAN MADORI INJECTION SUBSTATION MALAM MADORI TOWN. 8
179 D 11KV MATAZU MUSAWA INJECTION SUBSTATION MATAZU METROPOLITAN 8
180 D 11KV RIMIN KEBE SMALL SCALE INJECTION SUBSTATION RIMIN KEBE AND ZANGO DAKATA AREA. 8
181 D 11KV SAGAGI ADO BAYERO INJECTION SUBSTATION SAGAGI AND LOKON MAKERA AREA. 8
182 D 11KV TALAMIZ JOGANA INJECTION SUBSTATION GUNDUWAWA, KAKARA AND JOGANA AREA. 8
183 D 11KV TSAMIYA BABBA JOGANA INJECTION SUBSTATION TOKARAWA, GUNDUWAWA AND BABAWA AREA ALONG HADEJIA ROAD. 8
184 D 11KV TUDUN MURTALA SMALL SCALE INJECTION SUBSTATION TUDUN MURTALA AND TAGARJI AREAS. 8
185 D 11KV TUDUN WADA BRISCOE INJECTION SUBSTATION GAMA AND GAWAUNA AREA BRIGADE. 8
186 D 33KV BAGAUDA KUMBOTSO TS KUMBOTSO LGA, YANKUSA, DANGWAURO, KWANAR DAWAKI AND BUNKURE AREA. 8
187 D 33KV BIRNIWA HADEJIA TS BIRNIWA AND TARUBU AND GARIN MAGAJI AREA. 8
188 D 33KV GUJUNGU TAMBURAWA TS ENTIRE GUJUNJU TOWN 8
189 D 33KV JAHUN DUTSE TS KARNAYA, CHAI CHAI, RINGIM AND TAURA TOWN. 8
190 D 33KV MALUMFASHI FUNTUA TS BAKORI, KAFUR, DANA AND KANKARA 8
191 D 33KV POLYTECHNIC KATSINA TS RIMI AND BATAGARAWA 8
192 D 33KV SUMAILA DUTSE TS MOBILE BASE DANMASARA, KACHAKO AND PANDA ALONG MAIDUGURI ROAD. 8
193 E 11KV MAI RUWA TEXTILE INJECTION SUBSTATION ENTIRE MAIRUWA TOWN, KATSINA. 4
194 E 33KV DANDUME FUNTUA TS ENTIRE DANDUME TOWN AND SABUWA 4
195 E 33KV DAWANAU BUKAVU INJECTION SUBSTATION POLEWIRE LINE, JAJIRA, KATSINAWA AND DAWANAU AREAS. 4
196 E 33KV GARKO WUDIL TS INDABO, KWANAR SUMAILA, TAKAI AND GARKO TOWN. 4
197 E 33KV GAYA WUDIL INJECTION SUBSTATION GAYA, KADEMI AND AJINGI TOWN. 4
198 E 33KV GEZAWA SMALL SCALE INJECTION SUBSTATION ZAURAN DANBABA, ZANGON DAKATA, RANGAZA, GEZAWA AND KUNYA TOWN. 4
199 E 33KV KWANKWASO TAMBURAWA TS GARU, LAMBU, RIMIN GADO AND GWARZO TOWN. 4
200 E 33KV MAI ADUA DAURA TS MAI ADUA 4
`;

// Helper: Normalize lookup key
const normalizeLookupKey = (s) => {
  if (!s) return '';
  return String(s)
    .toLowerCase()
    .replace(/['’\u0060\u00b4]/g, '')
    .replace(/[-\s]/g, '')
    .normalize('NFKD')
    .replace(/[^a-z0-9]/g, '');
};

// Caching openstreetmap
const geocodeCacheFile = path.join(__dirname, 'geocode_cache.json');
let geocodeCache = {};
if (fs.existsSync(geocodeCacheFile)) {
  try { geocodeCache = JSON.parse(fs.readFileSync(geocodeCacheFile, 'utf8')); } catch(e){}
}
const saveGeocodeCache = () => fs.writeFileSync(geocodeCacheFile, JSON.stringify(geocodeCache, null, 2));

const geocode = async (query) => {
  if (geocodeCache[query]) return geocodeCache[query];
  try {
    const res = await axios.get('https://nominatim.openstreetmap.org/search', {
      params: { q: query, format: 'json', limit: 1 },
      headers: { 'User-Agent': 'Litha/1.0 (Kano_Import)' },
      timeout: 5000
    });
    if (res.data && res.data.length > 0) {
      const { lat, lon } = res.data[0];
      geocodeCache[query] = { latitude: parseFloat(lat), longitude: parseFloat(lon) };
      saveGeocodeCache();
      return geocodeCache[query];
    }
  } catch(e) {
    // console.log("Geocode failed for", query);
  }
  // Delay for OSM rules
  await new Promise(r => setTimeout(r, 1000));
  return null;
};

const BANNED_AREAS = [
  'KATSINA', 'JIGAWA', 'DAURA', 'FUNTUA', 'MUSAWA', 'KAZAURE', 
  'KANKIA', 'DUTSE', 'HADEJIA', 'BIRNIN KUDU', 'MALUMFASHI'
];

const parseFeeders = () => {
  const lines = OCR_TEXT.trim().split('\n');
  const feeders = [];
  for (const line of lines) {
    if (!line.trim()) continue;
    
    // Parse using regex
    // Format: <S/N> <BAND> <FEEDER NAME> <INJECTION SUBSTATION> <STREETS> <DURATION>
    // e.g. "1 A 11KV AHMADU BELLO CLUB INJECTION SUBSTATION AHMADU BELLO WAYAND MURTALA MUHD WAY KANO 20"
    // The "20" at the end is duration.
    
    const parts = line.split(' ');
    const sn = parts.shift();
    const band = parts.shift(); // A, B, C, D, E
    const duration = parts.pop();
    
    const text = parts.join(' ');
    // The trick is splitting feeder name, substation, streets.
    // Usually it goes: "<voltage> <name> <substation> <streets>"
    
    // 11KV or 33KV
    let voltageLevel = "11KV";
    if (text.includes("33KV")) voltageLevel = "33KV";
    
    // Find injection substation boundary. Usually ends with "INJECTION SUBSTATION", "INJECTION SUSTATION", "SUB STATION", "TS"
    const isMarkers = ['INJECTION SUBSTATION', 'INJECTION SUSTATION', 'SUB STATION', ' TS'];
    let subIndex = -1;
    let markerLen = 0;
    
    // We search from right to left or just find the first match
    for (const marker of isMarkers) {
      const idx = text.indexOf(marker);
      if (idx !== -1) {
        subIndex = idx;
        markerLen = marker.length;
        break;
      }
    }
    
    let feederNameRaw = text;
    let injectionSubstationRaw = "";
    let streetsRaw = "";
    
    if (subIndex !== -1) {
       // Feeder name is from start to the word before substation
       // E.g. "11KV AHMADU BELLO CLUB INJECTION SUBSTATION ..."
       // Wait, "CLUB INJECTION SUBSTATION" => Name is "11KV AHMADU BELLO", sub is "CLUB INJECTION SUBSTATION"
       // Let's split by the words ending at the marker.
       const leftPart = text.substring(0, subIndex + markerLen);
       streetsRaw = text.substring(subIndex + markerLen).trim();
       
       // Now split leftPart into feederName and Substation.
       // E.g. "11KV AHMADU BELLO CLUB INJECTION SUBSTATION"
       // The PDF has the column names: FEEDER NAME | DESCRIPTION OF FEEDER LOCATION (Substation)
       // Looking at row 1: "11KV AHMADU BELLO" "CLUB INJECTION SUBSTATION"
       // Unfortunately it's not separated by a clear delimiter.
       
       // Heuristic: If we know voltage is at the start (e.g. 11KV)
       // We can extract feeder name up to some point.
       // Actually, we can use the original line to match against BANNED_AREAS
       if (BANNED_AREAS.some(area => line.toUpperCase().includes(area))) {
          continue; // Skip
       }
       
       // Just keeping the whole left part as raw, we can refine or just store it.
       // We will assign a clean name.
       feederNameRaw = leftPart.trim();
    } else {
       if (BANNED_AREAS.some(area => line.toUpperCase().includes(area))) continue;
    }
    
    feeders.push({
      sn, band, voltageLevel, rawText: text, duration, leftPart: feederNameRaw, streetsRaw
    });
  }
  return feeders;
};

const report = {
  totalProcessed: 0,
  imported: 0,
  updated: 0,
  skipped: 0,
  duplicateRecordsAvoided: 0,
  missingCommunities: [],
  uncertainMappings: [],
  outsideKano: 0,
  validationErrors: [],
  successRate: 0,
};

const run = async () => {
  const uri = process.env.MONGODB_URI || process.env.MONGO_URI;
  if (!uri) {
    console.error('MongoDB URI missing. Aborting.');
    process.exit(1);
  }
  try {
     await mongoose.connect(uri);
  } catch(e) {
     console.error('Cannot connect to DB', e.message);
     process.exit(1);
  }
  
  const lookupPath = path.join(__dirname, 'communityLookup.json');
  let lookup = {};
  if (fs.existsSync(lookupPath)) {
    try { lookup = JSON.parse(fs.readFileSync(lookupPath, 'utf8')); } catch (e) {}
  }
  
  const parsedFeeders = parseFeeders();
  
  for (const f of parsedFeeders) {
    report.totalProcessed++;
    
    const uniqueId = `FDR-KAN-${f.sn.padStart(4, '0')}`;
    
    // We need to parse streetsRaw into potential communities
    const streetTokens = f.streetsRaw.split(/[,&]+/i).map(s => s.trim()).filter(Boolean);
    
    let communityIds = [];
    let wardIds = new Set();
    let lgaIds = new Set();
    
    let allTokensConfident = true;
    let mappedCommunities = [];
    
    // Split further by ' AND '
    let subTokens = [];
    for (const st of streetTokens) {
        subTokens.push(...st.split(/\s+AND\s+/i));
    }
    
    const STOP_WORDS = ['KANO', 'STATE', 'CITY', 'AREA', 'AREAS', 'ROAD', 'RD', 'TOWN', 'VILLAGE', 'STREET', 'ST', 'WAY', 'QUARTERS', 'ESTATE', 'HUB', 'TS', 'NEW', 'OLD', 'METROPOLITAN', 'METRO'];
    
    for (let token of subTokens) {
      // Remove stop words as whole words
      let cleanToken = token;
      for (const sw of STOP_WORDS) {
         const regex = new RegExp('\\\\b' + sw + '\\\\b', 'gi');
         cleanToken = cleanToken.replace(regex, '');
      }
      cleanToken = cleanToken.trim();
      if (!cleanToken) continue; // Skip if it was just a stop word
      
      const nKey = normalizeLookupKey(cleanToken);
      
      if (nKey && lookup[nKey] && lookup[nKey].length > 0) {
        // exact matches in lookup
        for (const c of lookup[nKey]) {
           const dbWard = await Ward.findOne({ id: c.communityId });
           if (dbWard) {
              communityIds.push(dbWard._id);
              wardIds.add(dbWard._id.toString());
              lgaIds.add(dbWard.lga.toString());
              mappedCommunities.push({ name: dbWard.name, lat: dbWard.latitude, lng: dbWard.longitude });
           }
        }
      } else {
        // Not 100% confidence
        allTokensConfident = false;
      }
    }
    
    if (!allTokensConfident || communityIds.length === 0) {
      report.uncertainMappings.push({ raw: f.rawText, uniqueId });
      report.missingCommunities.push(f.streetsRaw);
      report.skipped++;
      continue;
    }
    
    // Check Substation
    // "11KV AHMADU BELLO CLUB INJECTION SUBSTATION" -> let's extract Substation
    let subName = "Unknown Substation";
    let fName = f.leftPart;
    if (f.leftPart.includes("INJECTION SUBSTATION")) {
       const parts = f.leftPart.split("INJECTION SUBSTATION");
       const potentialName = parts[0].trim().split(" ");
       const subPart = potentialName.pop();
       subName = `${subPart} INJECTION SUBSTATION`;
       fName = potentialName.join(" ");
    } else if (f.leftPart.includes(" TS")) {
       const parts = f.leftPart.split(" TS");
       const potentialName = parts[0].trim().split(" ");
       const subPart = potentialName.pop();
       subName = `${subPart} TS`;
       fName = potentialName.join(" ");
    }
    
    // Substation Model
    let subSlug = slugify(subName);
    let subDoc = await InjectionSubstation.findOne({ slug: subSlug });
    if (!subDoc) {
       subDoc = await InjectionSubstation.create({ name: subName, slug: subSlug, uniqueId: `SUB-${Date.now()}` });
    }
    
    let feederSlug = slugify(fName);
    
    // Geocode centroid
    let centroid = { latitude: null, longitude: null };
    let validCoords = mappedCommunities.filter(c => c.lat !== null && c.lng !== null);
    if (validCoords.length > 0) {
       centroid.latitude = validCoords.reduce((sum, c) => sum + c.lat, 0) / validCoords.length;
       centroid.longitude = validCoords.reduce((sum, c) => sum + c.lng, 0) / validCoords.length;
    } else {
       // OpenStreetMap
       const geo = await geocode(f.streetsRaw + ", Kano, Nigeria");
       if (geo) {
          centroid = geo;
       }
    }
    
    // Insert / Update
    try {
      const existing = await Feeder.findOne({ $or: [{ uniqueId }, { slug: feederSlug }] });
      
      const updateData = {
        uniqueId,
        slug: feederSlug,
        name: fName,
        displayName: fName,
        band: f.band,
        voltageLevel: f.voltageLevel,
        injectionSubstation: subName,
        injectionSubstationId: subDoc._id,
        communityIds: [...new Set(communityIds)],
        wardIds: Array.from(wardIds),
        lgaId: Array.from(lgaIds)[0] || null,
        source: 'KEDCO',
        verificationStatus: 'Verified',
        confidenceScore: 100,
        status: 'active',
        coordinates: (centroid.latitude && centroid.longitude) ? centroid : null
      };
      
      if (existing) {
         await Feeder.updateOne({ _id: existing._id }, updateData);
         report.updated++;
         report.duplicateRecordsAvoided++;
      } else {
         await Feeder.create(updateData);
         report.imported++;
      }
    } catch(err) {
      report.validationErrors.push({ uniqueId, error: err.message });
      report.skipped++;
    }
  }
  
  report.successRate = ((report.imported + report.updated) / report.totalProcessed) * 100;
  
  fs.writeFileSync(path.join(__dirname, 'missing_communities.json'), JSON.stringify({ missing: report.missingCommunities, uncertain: report.uncertainMappings }, null, 2));
  
  console.log("Validation Report:", JSON.stringify(report, null, 2));
  
  await mongoose.disconnect();
  process.exit(0);
};

run();
